### ISSUE TITLE
Command 22 is Broken

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WASharpIssues#10]
~~I wasn't exactly sure what to call this since I'm not 100% sure what is happening.~~

~~The adventure that comes with the Editor "Timing is Everything!" (Matthieu#movingblink) seems to be impossible due to a general command button not being activated. Normally, the first NPC Barrel you encounter (by the purple gate) should have it's dialog starting interchange changed after speaking to the second NPC Barrel (by the purple button). This is done by lowering a gate that releases a +100 speed Spikeyball that should pass over the general command button before being destroyed by water. This mechanism is hidden away by fake walls. Every time I speak to the second NPC Barrel for the first time, I can hear the Spikeyball exploding, but the interchange is always the same.~~

EDIT: I think I figured out what's happening - I think it's just command 22 in general that's broken. It doesn't seem to have anything to do with the particular mechanism in the adventure I mentioned before.

**Comment by Aryan807** [comment]
Fixed, thanks for reported.
