### ISSUE TITLE
[WA1] Game crashes when entering Wonderland Adventure Level 1

### ISSUE THREAD

**Issue by vPubneutral** [HumanGamer/WASharpIssues#13]
Like the title says

Steps to reproduce, done on WA# 11.0.0.beta.1:
1. Go to the Arcade in Wondertown
2. Enter Level 1 of "Wonderland Adventure" (use token if necesarry)
3. Game crashes after continuing from the adventure description

This issue does not occur in Vanilla WA, or OpenWA 10.3.2. I've correctly installed WA# using the instructions in the "washarp_readme.txt" (Install on top of a fresh copy of the vanilla WA editor, without archive) and the issue occurs on copies of the game installed to WA# using both the Hub Manager and the manual installation detailed in "how_to_gameswitch.txt". This issue does not occur on levels 2 or 3 of the "Wonderland Adventure" arcade cabinet.

Log: 
[wg.log](https://github.com/HumanGamer/WASharpIssues/files/9180553/wg.log)

Player profile (with save) for testing:
[save.zip](https://github.com/HumanGamer/WASharpIssues/files/9180416/save.zip)

Temp workaround for players: Save at any point before entering the level, copy your profile in
`"[WA# directory]\GameData\WA1\Player Profiles\[profile name]"`
to an instance of OpenWA 10.3.2 at
`"[OpenWA directory]\GameData\WA1\Player Profiles\[profile name]",`
then load the save in OpenWA and complete the adventure. Once you have finished, save, exit, then copy the OpenWA save back to your WA# instance,

**Comment by Aryan807** [comment]
Oh my! The bug is actually due to the fact that the wlvs of that adventure don't store last two variables which include weather and level music. This makes WA# engine crash as it is very strict in checking variables in file.

**Comment by Aryan807** [comment]
Fixed, thanks for reporting.
