### ISSUE TITLE
Dialogs are hard to read when opening them with Vault

### ISSUE THREAD

**Issue by jdl96** [HumanGamer/WASharpIssues#5]
If you open a Dialog file with Command 21 in the Vault, the first interchange is usually going to be skipped due to the Enter key being used to close the Vault. If you press the Enter key for 1 frame, the first interchange is shown.

EDIT: I've also noticed that there are a little bit more lag frames when exiting the Vault than the original game. I'm not sure if that has anything to do with it.

**Comment by Aryan807** [comment]
Thanks for reporting the bug, it is fixed now.

Along with that there was also a bug in which pressing UP/DOWN keys during the dialogs with multiple replies or in askabout mode did not scroll. This was unrelated to this one, but it made me discover it by accident. This is also fixed now.
